project:
  type: website
  # TODO: use GitHub Actions?

website:
  title: "Ehud Karavani"
  description: >
    a researcher and data scientist, 
    specializing in causal inference, machine learning, 
    (Bayesian) statistics, and data visualization.
  favicon: img/bar-chart-fill.svg
  twitter-card: true
  open-graph: true
  navbar:
    # pinned: true
    left:
      - text: About
        href: index.qmd
      - text: CV
        href: cv/index.qmd
      - text: Publications
        href: publications/index.qmd
      - text: Materials
        href: materials/index.qmd
      - text: Blog
        href: blog/index.qmd
    right:
      # icons from https://icons.getbootstrap.com/
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/ehudk
        rel: me 
        target: "_new"
      - text: "{{< iconify simple-icons googlescholar size=lg >}}"  # https://icon-sets.iconify.design/
        aria-label: google-scholar
        href: https://scholar.google.com/citations?user=KAzt_pYAAAAJ&hl=en
        rel: me 
        target: "_new"
      - icon: github
        aria-label: github
        href: https://github.com/ehudkr
        rel: me  
        target: "_new"
      - icon: medium
        aria-label: medium
        href: https://medium.com/@ehudkr
        rel: me  
        target: "_new"
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/ehudkar
        rel: me 
        target: "_new"
      - text: "{{< iconify fluent-emoji blue-square >}}"
        href: https://bsky.app/profile/ehudk.bsky.social
        rel: me  
        target: "_new"
      - icon: mastodon
        aria-label: mastodon
        href: https://mastodon.social/@ehudk
        rel: me  # For verification: https://github.com/quarto-dev/quarto-cli/pull/3333
        target: "_new"
      - icon: stack-overflow
        aria-label: stack-overflow
        href: https://stackoverflow.com/users/7708413/ehudk
        rel: me  
        target: "_new"
      # - text: "{{< iconify cib stackexchange >}}"
      #   aria-label: cross-validated
      #   href: https://stackoverflow.com/users/7708413/ehudk
      #   rel: me 
      #   target: "_new"
      - text: "{{< iconify simple-icons discourse >}}"
        aria-label: datamethods
        href: https://discourse.datamethods.org/u/ehudk/summary
        rel: me  
        target: "_new"
  repo-url: https://github.com/ehudkr/ehudkr.github.io/
  repo-actions: [source, edit, issue]
  google-analytics: "G-66TLP1EVBH"
      
format:
  html:
    theme: 
      light: cosmo
      dark: [darkly, dark-theme.scss]
    css: styles.css
    toc: true
    link-external-newwindow: true
  
resources: 
  - CNAME  # https://github.com/quarto-dev/quarto-cli/discussions/3249

pagetitle: "{{< meta title >}} | Ehud Karavani"
author-meta: "Ehud Karavani"
