project:
  type: website
  # TODO: use GitHub Actions?

website:
  title: "Ehud Karavani"
  navbar:
    # pinned: true
    left:
      - text: About
        href: index.qmd
      - text: CV
        href: cv/index.qmd
      - text: Publications
        href: publications/index.qmd
      - text: Materials
        href: materials/index.qmd
      - text: Blog
        href: blog/index.qmd
    right:
      # icons from https://icons.getbootstrap.com/
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/ehudk
        rel: me 
      - text: "{{< iconify simple-icons googlescholar size=lg >}}"  # https://icon-sets.iconify.design/
        aria-label: google-scholar
        href: https://scholar.google.com/citations?user=KAzt_pYAAAAJ&hl=en
        rel: me 
      - icon: github
        aria-label: github
        href: https://github.com/ehudkr
        rel: me  
      - icon: medium
        aria-label: medium
        href: https://medium.com/@ehudkr
        rel: me  
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/ehudkar
        rel: me 
      - icon: mastodon
        aria-label: mastodon
        href: https://mastodon.social/@ehudk
        rel: me  # For verification: https://github.com/quarto-dev/quarto-cli/pull/3333
      - icon: stack-overflow
        aria-label: stack-overflow
        href: https://stackoverflow.com/users/7708413/ehudk
        rel: me  
      # - text: "{{< iconify cib stackexchange >}}"
      #   aria-label: cross-validated
      #   href: https://stackoverflow.com/users/7708413/ehudk
      #   rel: me 
      - text: "{{< iconify simple-icons discourse >}}"
        aria-label: datamethods
        href: https://discourse.datamethods.org/u/ehudk/summary
        rel: me  
      
format:
  html:
    theme: 
      light: [cosmo, light-theme.scss]
      dark: [darkly, dark-theme.scss]
    css: styles.css
    toc: true
    link-external-newwindow: true
    # link-external-filter: ^(?:http:|https:)\/\/ehudkr\.github\.io



