project:
  type: website
  # TODO: use GitHub Actions?

website:
  title: "Ehud Karavani"
  navbar:
    # pinned: true
    left:
      - text: About
        href: index.qmd
      - text: CV
        href: cv/index.qmd
      - text: Publications
        href: publications/index.qmd
      - text: Materials
        href: materials/index.qmd
      - text: Blog
        href: blog/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



