project:
  type: website
  output-dir: docs  # TODO: use GitHub Actions instead?

website:
  title: "ehudkr.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



